### ISSUE TITLE
HABBase vs Lora Gateway Reporting Differences

### ISSUE THREAD

**Issue by KevWal** [daveake/HABBase#10]
Hi Dave

Uploading via HabBase and Lora Gateway gives some differences shown on sondehub:

![image](https://user-images.githubusercontent.com/2286500/195441634-cfc34f6c-bd28-40e3-87a8-9ed7ede7acff.png)

The batt field (9 Battery Voltage) looks to be in mV on HAB base but V on lora-gateway, and temperature (A InternalTemperature) seems to come through as temp on HAB Base but internal_temp via Lora Gateway?

My transmitted sentence:
$$KW-BCK,39044,19:53:55,52.32264,-0.70617,99,5,17.0,1.88,1.37,0123456AI9*C8E4

Sentances as shown by grafana.v2.sondehub.org:

{"software_name":"HAB Base","software_version":"V1.6.9","uploader_callsign":"G7PMO_LoraBT","time_received":"2022-10-12T19:52:23Z","payload_callsign":"KW-BCK","datetime":"2022-10-12T19:52:06Z","lat":52.32272,"lon":-0.70619,"alt":92,"frequency":433.653,"temp":19,"batt":0.0014,"sats":7,"modulation":"LoRa (Mode 5)","snr":6,"rssi":-73,"uploader_position":"52.3,-0.7","raw":"$$KW-BCK,39039,19:52:06,52.32272,-0.70619,92,7,19.0,1.89,1.42,0123456AI9*15FC","user-agent":"Amazon CloudFront","position":"52.32272,-0.70619","uploader_alt":100}
2022-10-12 19:52:06	

{"software_name":"LoRa Gateway","software_version":"V1.9.5","uploader_callsign":"G7PMO_PiRx","time_received":"2022-10-12T19:52:30Z","payload_callsign":"KW-BCK","datetime":"2022-10-12T19:52:06Z","lat":52.32272,"lon":-0.70619,"alt":92,"frequency":433.655,"modulation":"LoRa Mode 5","snr":6,"rssi":-83,"raw":"$$KW-BCK,39040,19:52:06,52.32272,-0.70619,92,7,19.0,1.89,1.43,0123456AI9*D90C","sats":7,"internal_temp":19,"batt":1.43,"uploader_position":"52.322,-0.706","uploader_antenna":"Colinear","user-agent":"Amazon CloudFront","position":"52.32272,-0.70619","uploader_alt":0}

Thanks very much
Kev

**Comment by daveake** [comment]
Cheers, I'll add the multiplier and unify the field names.

Dave

**Comment by daveake** [comment]
New versions will be out today:

   - Both receivers will emit the battery value in volts.
   - Both receivers will check the incoming battery value; if it contains a
   decimal point then it's interpreted as volts if not it's interpreted as mV.
   - HAB Base was sending internal or external temperatures as "temp"; now
   it's the same as the gateway with "internal_temp" and "temp" for external
   - HAB Base now sends the modulation in the same format as the gateway
   e.g. "LoRa Mode 1"

Dave

**Comment by KevWal** [comment]
Fantastic, you are a star Dave, thankyou! 🥰

P.s. do you have a release date or any chance of a beta of the new HABExplora please 😊

**Comment by daveake** [comment]
Planning on doing the app store thing tomorrow.

**Comment by daveake** [comment]
Fixed in V1.7.0 which is going to the play store now.

**Comment by daveake** [comment]
Fixed in current release.

**Comment by KevWal** [comment]
Just FYI I have opened one issue for sondehub-amateur-tracker related to your revised approach:

https://github.com/projecthorus/sondehub-amateur-tracker/issues/68

Cheers
Kev

**Comment by daveake** [comment]
HAB Base should follow what sondehub expects, not the other way round.  Let
me know what it expects please.

**Comment by KevWal** [comment]
No problem, looking at grafana.v2.sondehub.org these are all the ones used in the general dashboard:

"field": "alt"
"field": "batt",
"field": "sats"
"field": "ascent_rate"
"field": "temp",
"field": "ext_temperature"
"field": "ext_pressure"
"field": "ext_humidity"
"field": "frequency"
"field": "snr"

"temp" is the only one I can show an issue with - although I dont have a payload that uploads the other environmental style ones.

These dont quite match up to the format listed here:  https://github.com/projecthorus/sondehub-infra/wiki/API-(Beta), although both (wiki and api doc) do define (internal) temperature as "temp".

Thanks very much
Kev

**Comment by daveake** [comment]
Ta, l have a chat with Mark first.
