### ISSUE TITLE
Wrong date string in logs

### ISSUE THREAD

**Issue by Medvidas** [daveake/HABBase#17]
Hi,
the date string in all the log files - sources/payload/uploads is wrongly formated.
The month substring is identical to the minute. See examples bellow:
2023-**47**-17 12:47:56,,,10:47:45,45.5712,9.4628,162,,,,,,,,,,,,,,,,,,,,0.0,698.9,225.2,-3.1
2023-**41**-18 19:41:06,,,17:40:09,51.4901,3.8236,4,,,,,,,,,,,,,,,,,,,,0.0,854.4,284.4,-3.9
The new log files greatly extend the app usability and interoperability, this bug is not so critical. 
Thank you

**Comment by daveake** [comment]
Oops, I did see that briefly in testing and thought I'd fixed it.  I'll get
that done tomorrow.

**Comment by daveake** [comment]
Fixed in V1.7.6
