### ISSUE TITLE
Wrong hab icon latitude on Leaflet maps

### ISSUE THREAD

**Issue by Medvidas** [daveake/HABBase#18]
The position of Hab icon and predicted landing point (cross) icon is not properly displayed on the newly introduced Leaflet map.
It looks like longitude is ok, but latitude is miscalculated. That is good visible as the zoom is changed.
It is documented on the attached screenshot. The actual HAB icon position should be as indicated by orange dots.

That is Habbase behaviour of my installation - V1.7.7, Windows 10, CZE locale.
![Icon latitude issue](https://github.com/daveake/HABBase/assets/57909431/ccd68530-95b7-4072-8608-07610c527590)

**Comment by daveake** [comment]
Thanks, I've confirmed this and I'll take it up with the map library supplier.

**Comment by daveake** [comment]
I have an update for you.  The supplier initially couldn't reproduce the issue but digging deeper they discovered that it only happens with rectangular rather than square marker icons.  They are looking in to fixing this behaviour.

Meanwhile, I will look at either removing leaflet support for now, or changing all of the markers (27 of them!) to be square.

**Comment by Medvidas** [comment]
While OSM, Tomtom, Google,... everything but Leaflet maps is working well within HABbase, it make sense IMHO to let Leaflet team fix their code. There are alternative maps in HABbase which are ok.

**Comment by daveake** [comment]
Map supplier has accepted the issue and I await their fix.  Meanwhile I've updated the software/installer with the Leaflet option removed.

**Comment by Medvidas** [comment]
Hi Dave, 
I'm testing version 1.7.10 and although map rendering via Leaflet is disabled since version 1.7.7, it is still active when I start the program.  Take a look at the screenshot. Clicking on the map selection button "OPEN" (or other) loads the correct map.
Have you tried if the new versions of the Leaflet still have the wrong icon placement? 
Leaflet is IMHO fastest renderer and it's a pitty you had to turn it off.
![Habbase 1 7 10 icon shift after start](https://github.com/user-attachments/assets/20a371ce-f853-4783-b198-96acb9edb60d)
