### ISSUE TITLE
Setting LoRa QRG from Channel window takes ages by large changes. Allow entering QRG please

### ISSUE THREAD

**Issue by zanco** [daveake/HABBase#5]
Hi Dave, could you make it possible to enter the frequency by keyboard also in the "channel 1" "channel 2" display ? Sometimes we switch from 432 to 434 and that's a lot of arrow presses.

You can click in the QRG field but not change it.

**Comment by daveake** [comment]
Fixed in V1.1.0:

1. - Frequency box is now editable
2. - On moving focus from that box (tab/mouse) the new frequency is sent to the receiver
3. - All frequency changes are added to the log window
4. (1) thru (3) apply equally to the LoRa Serial and LoRa Gateway sources.
