### ISSUE TITLE
Signal meters in Sources are not equally positoned. 

### ISSUE THREAD

**Issue by zanco** [daveake/HABBase#7]
Not doing any harm to functionality, but in (LoRa) source with 2 receiver channels, switching from Channel 0 to Channel 1 the signal meters do shift some pixels.

Channel 1 appear to have a bit more height in pixels.

Nice to see channel 0 and 1 instead of 1 and 2 :-)

Great job!

**Comment by daveake** [comment]
Fixed in V1.7.3, to be released soon.
