### ISSUE TITLE
Balloon Filters not working as expected

### ISSUE THREAD

**Issue by KevWal** [daveake/HABBase#8]
Hi Dave 

It may be my misunderstanding, but the Balloon Filters section doesn't seem to be working for me.  I wanted to reduce the distance that I was seeing Sonde's over, but leave the distance for everything else the same, so I configured it as per the attached:

![image](https://user-images.githubusercontent.com/2286500/108884749-da53cc80-75fe-11eb-9c75-bbd7ca840025.png)

However this didn't show Sonde's that were less than 1000km, to double check I configured it as:

![image](https://user-images.githubusercontent.com/2286500/108884564-a678a700-75fe-11eb-9632-3772314c32d4.png)

and it still didn't show the sondes that it shows in the default 1 filter line, everything enabled, 5000km configuration?

Thanks
Kevin

**Comment by daveake** [comment]
You need "remote" checked for Sondes too - it should be checked for
anything coming in from logtail.

**Comment by KevWal** [comment]
Working nicely now I understand that, thank you :)

Cheers
Kev
