### ISSUE TITLE
Lora Serial Source includes other Habbitat payloads?

### ISSUE THREAD

**Issue by KevWal** [daveake/HABBase#9]
Hi

Running v1.6.0 with 2 Sources configured, and my Lora Serial source seems to be showing payloads recieved in the Status window that I can not possibly be recieving:

![image](https://user-images.githubusercontent.com/2286500/183242797-0e59a6b5-3095-4ff2-8107-0314ab2b5ac0.png)

I had previously configured a Habitat source (to see the difference between it and Log Tail), but since deleted it as I didn't really know what it was doing - but the data showing up in my Lora Serial source looks very similar to that that was in the Habitat source?

Thanks
Kevin

**Comment by daveake** [comment]
Thanks, that's a weird one.  It shouldn't be keeping any history nor should
information cross from one source to another.  I'll check.

Dave

**Comment by KevWal** [comment]
Thanks Dave,

Currently I have 2 x LoraSerial log sources connected on different com ports, and I seem to be getting some more corruption:

![image](https://user-images.githubusercontent.com/2286500/195186905-6211c7da-8422-433e-b875-005f5250291d.png)

Where as Lora-gateway is getting the packet fine:
20:56:32 Ch0: $$KW-BCK,34328,19:54:48,52.32263,-0.70629,95,8,0.0,1.88,1.96,0123456A9I*FEF3

**Comment by daveake** [comment]
I'll set up a test for that.

Dave

**Comment by KevWal** [comment]
Thanks Dave, another example incase is helpful:

![image](https://user-images.githubusercontent.com/2286500/195199123-de004f61-1a07-4ee3-ba0c-8822acf8f38a.png)

22:07:17 Ch0: $$KW-BCK,34743,20:59:03,52.32271,-0.70621,85,8,24.0,1.88,1.96,0123456A9I*CA84
22:07:34 Ch0: $$KW-BCK,34744,20:59:03,52.32271,-0.70621,85,8,24.0,1.88,1.95,0123456A9I*85E2
22:08:23 Ch0: $$KW-BCK,34745,21:08:04,52.32257,-0.70614,102,7,20.0,1.88,1.96,0123456A9I*7C4C
22:08:40 Ch0: $$KW-BCK,34746,21:08:04,52.32257,-0.70614,102,7,23.0,1.88,1.95,0123456A9I*FD26
22:08:57 Ch0: $$KW-BCK,34747,21:08:04,52.32257,-0.70614,102,7,23.0,1.88,1.95,0123456A9I*4669
22:09:14 Ch0: $$KW-BCK,34748,21:08:04,52.32257,-0.70614,102,7,23.0,1.88,1.95,0123456A9I*DC3A
22:09:31 Ch0: $$KW-BCK,34749,21:08:04,52.32257,-0.70614,102,7,23.0,1.88,1.96,0123456A9I*62EA
22:09:48 Ch0: $$KW-BCK,34750,21:08:04,52.32257,-0.70614,102,7,24.0,1.88,1.95,0123456A9I*8A5E

**Comment by KevWal** [comment]
And if the corruption is in the callsign, it does get through to sondehub:

![image](https://user-images.githubusercontent.com/2286500/195199537-81740384-23fe-45ae-882d-c6db8835e6cf.png)

I think 7 of these are from my one payload :(

**Comment by daveake** [comment]
Error found I'll fix in the morning.

Dave

**Comment by daveake** [comment]
Try this please:

https://www.dropbox.com/s/4l92b58gw170llo/HABBase.exe?dl=0

I don't have time to test with 2 serial till tomorrow but this should fix
it.

Dave

**Comment by KevWal** [comment]
Looking promising, thankyou!

I did get a few errors on startup:

![image](https://user-images.githubusercontent.com/2286500/195283653-44ab0056-ccf3-4043-bd30-a1aeb5542f21.png)

But after that all good:

![image](https://user-images.githubusercontent.com/2286500/195283763-72036040-f044-4588-b39b-757746def005.png)

Thanks so much :)

Cheers
Kev

**Comment by daveake** [comment]
The edge support is included in the installer; this was just a replacement
exe.

I'll get a new installer sorted today.

Dave

**Comment by daveake** [comment]
Fixed in latest installer.
